-- V1__init.sql : initial TutorHub schema
-- Column names/types match the JPA entities so Hibernate's
-- spring.jpa.hibernate.ddl-auto=validate passes on startup.

create table academy (
                         id          bigint generated by default as identity primary key,
                         name        varchar(255) not null,
                         slug        varchar(255) not null unique,
                         created_at  timestamp(6) with time zone not null,
                         updated_at  timestamp(6) with time zone not null
);

create table app_user (
                          id            bigint generated by default as identity primary key,
                          email         varchar(255) not null unique,
                          password_hash varchar(255) not null,
                          display_name  varchar(255) not null,
                          created_at    timestamp(6) with time zone not null,
                          updated_at    timestamp(6) with time zone not null
);

create table membership (
                            id          bigint generated by default as identity primary key,
                            user_id     bigint not null references app_user(id),
                            academy_id  bigint not null references academy(id),
                            role        varchar(20) not null,
                            created_at  timestamp(6) with time zone not null,
                            updated_at  timestamp(6) with time zone not null,
                            constraint uq_membership_user_academy unique (user_id, academy_id)
);
create index idx_membership_academy on membership(academy_id);
create index idx_membership_user on membership(user_id);

create table course (
                        id          bigint generated by default as identity primary key,
                        academy_id  bigint not null references academy(id),
                        title       varchar(255) not null,
                        subject     varchar(255) not null,
                        term        varchar(255) not null,
                        tutor_id    bigint references app_user(id),
                        created_at  timestamp(6) with time zone not null,
                        updated_at  timestamp(6) with time zone not null
);
create index idx_course_academy on course(academy_id);
create index idx_course_tutor on course(tutor_id);

create table enrollment (
                            id          bigint generated by default as identity primary key,
                            course_id   bigint not null references course(id),
                            student_id  bigint not null references app_user(id),
                            enrolled_at timestamp(6) with time zone not null,
                            created_at  timestamp(6) with time zone not null,
                            updated_at  timestamp(6) with time zone not null,
                            constraint uq_enrollment_course_student unique (course_id, student_id)
);
create index idx_enrollment_course on enrollment(course_id);
create index idx_enrollment_student on enrollment(student_id);

create table assignment (
                            id           bigint generated by default as identity primary key,
                            course_id    bigint not null references course(id),
                            title        varchar(255) not null,
                            instructions text,
                            due_date     timestamp(6) with time zone not null,
                            max_score    integer not null,
                            created_at   timestamp(6) with time zone not null,
                            updated_at   timestamp(6) with time zone not null
);
create index idx_assignment_course on assignment(course_id);

create table submission (
                            id            bigint generated by default as identity primary key,
                            assignment_id bigint not null references assignment(id),
                            student_id    bigint not null references app_user(id),
                            content       text,
                            status        varchar(20) not null,
                            score         integer,
                            version       bigint not null default 0,
                            created_at    timestamp(6) with time zone not null,
                            updated_at    timestamp(6) with time zone not null,
                            constraint uq_submission_assignment_student unique (assignment_id, student_id)
);
create index idx_submission_assignment on submission(assignment_id);
create index idx_submission_student on submission(student_id);

create table feedback (
                          id            bigint generated by default as identity primary key,
                          submission_id bigint not null references submission(id),
                          author_id     bigint not null references app_user(id),
                          body          text not null,
                          created_at    timestamp(6) with time zone not null,
                          updated_at    timestamp(6) with time zone not null
);
create index idx_feedback_submission on feedback(submission_id);
create index idx_feedback_author on feedback(author_id);